// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjSnvO06RbUExn05alOnlGMim_GS1UTtk',
    appId: '1:887685447052:web:30475d1dc6741208186aa9',
    messagingSenderId: '887685447052',
    projectId: 'ufukatay-todo-2a9f8',
    authDomain: 'ufukatay-todo-2a9f8.firebaseapp.com',
    storageBucket: 'ufukatay-todo-2a9f8.appspot.com',
    measurementId: 'G-5YQEJHEFDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFGhCpCNUueIuKatXqvrIIa2YLOmkhe5I',
    appId: '1:887685447052:android:5081069b31b6c70c186aa9',
    messagingSenderId: '887685447052',
    projectId: 'ufukatay-todo-2a9f8',
    storageBucket: 'ufukatay-todo-2a9f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAscD0p5bmO4_jITrU7H3S82IHJhxPTdkM',
    appId: '1:887685447052:ios:271d22b1d258fc2d186aa9',
    messagingSenderId: '887685447052',
    projectId: 'ufukatay-todo-2a9f8',
    storageBucket: 'ufukatay-todo-2a9f8.appspot.com',
    iosBundleId: 'com.example.ufukatayTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAscD0p5bmO4_jITrU7H3S82IHJhxPTdkM',
    appId: '1:887685447052:ios:271d22b1d258fc2d186aa9',
    messagingSenderId: '887685447052',
    projectId: 'ufukatay-todo-2a9f8',
    storageBucket: 'ufukatay-todo-2a9f8.appspot.com',
    iosBundleId: 'com.example.ufukatayTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjSnvO06RbUExn05alOnlGMim_GS1UTtk',
    appId: '1:887685447052:web:41c3c14b996ad307186aa9',
    messagingSenderId: '887685447052',
    projectId: 'ufukatay-todo-2a9f8',
    authDomain: 'ufukatay-todo-2a9f8.firebaseapp.com',
    storageBucket: 'ufukatay-todo-2a9f8.appspot.com',
    measurementId: 'G-1VRFKXGZQM',
  );
}
